"""initial migration

Revision ID: 4464a7655f80
Revises:
Create Date: 2026-09-03 15:28:39.147060

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4464a7655f80"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
