"""add model description

Revision ID: 688b33d069ab
Revises: 4464a7655f80
Create Date: 2026-09-04 01:00:46.108746

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "688b33d069ab"
down_revision: str | Sequence[str] | None = "4464a7655f80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_models", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "description")
    # ### end Alembic commands ###
