"""add user role

Revision ID: 9e922ca5a993
Revises: 5770eba085a1
Create Date: 2026-09-13 01:14:04.072968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e922ca5a993'
down_revision: Union[str, Sequence[str], None] = '5770eba085a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.String(),
        nullable=False,
        server_default='user'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
